version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.10
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - sam build
      - echo sam build completed
      - sam deploy --stack-name melody-journal-be --parameter-overrides Stage=$ENV_NAME --capabilities "CAPABILITY_IAM"
  post_build:
    commands:
      - echo Deployment completed