version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.10
  pre_build:
    commands:
      - sam --version
  build:
    commands:
      - sam package --template-file template.yml --stack-name melody-journal-be --parameter-overrides Stage=$ENV_NAME --capabilities "CAPABILITY_IAM"
  post_build:
    commands:
      - echo Deployment completed